### ISSUE TITLE
Bug in Bind Data

### ISSUE THREAD

**Issue by MorasDeFresa** [adammyhre/Unity-Inventory-System#4] opened 2024-04-22 00:13 UTC
When I use NewGame method the PlayerData doesn't take the values in Hero, position and rotation (In my case Farmer) Class but In Hero class data if change your value. The Data manager (SaveLoadSystem) not ;-; . This issue only occur if I use NewGame method

**Comment by adammyhre** [comment] 2024-04-22 00:31
This is not enough information to open an Issue.  If you can't understand how to implement the system from watching the video, then you should be asking for help on Discord in the correct forum related to the video - but be advised, Discord members are going to expect the same due diligence I'm telling you below:

If it is an actual bug then you must do 3 things:

1) Describe the actual problem as it relates to code in this repository (note the Hero class is NOT part of this repository) in a way people can understand
2) List steps that someone can take to replicate the issue
3) Provide a possible solution or AT LEAST provide details of your attempts to debug and confirm the bug

If you can't do those things, then this is not a bug and I'm going to close the Issue shortly.

**Closed as completed** 2024-04-22 12:31 UTC
